# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: bss
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: bss
    main: ./cmd/boot-script-service
    binary: boot-script-service
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    no_unique_dist_dir: false
    tags:
      - dynamic
  - id: bss-init
    main: ./cmd/bss-init
    binary: bss-init
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: false
    tags:
      - dynamic

dockers:
  - image_templates:
      - ghcr.io/openchami/{{.ProjectName}}:latest-amd64
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}-amd64
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-amd64
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: amd64
    use: buildx
    extra_files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - .version
      - migrations/
  - image_templates:
      - ghcr.io/openchami/{{.ProjectName}}:latest-arm64
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}-arm64
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-arm64
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64
    use: buildx
    extra_files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - .version
      - migrations/

docker_manifests:
- name_template: 'ghcr.io/openchami/{{.ProjectName}}:latest'
  image_templates:
  - 'ghcr.io/openchami/{{.ProjectName}}:latest-amd64'
  - 'ghcr.io/openchami/{{.ProjectName}}:latest-arm64'
- name_template: 'ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}-amd64'
  - 'ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}'
  image_templates:
  - 'ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-amd64'
  - 'ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-arm64'
- name_template: 'ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}'
  image_templates:
  - 'ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-amd64'
  - 'ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-arm64'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - CHANGELOG.md
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
